### PR TITLE
[DRAFT] initial pass at defining terminology in the readme

### PR DESCRIPTION
**Pull request by AevaOnline**
Signed-off-by: Aeva Black <806320+AevaOnline@users.noreply.github.com>

### CODE REVIEW

**Review by lehors — COMMENTED** [review]
LGTM but isn't this repo duplicative of this one: https://github.com/ossf/foundation

**Comment by jorydotcom** [comment]
@lehors this is a good question - what are we doing with the /foundation repo, how's it different (or not) from the goals of the /community repo, etc. I think /community is more common among open source projects for the kind of support materials we want to put here. @AevaOnline @bobcallaway can we (briefly) discuss at the TAC call?

**Comment by AevaOnline** [comment]
@lehors that's a very reasonable question, and I'll admit that I didn't even know about the /foundation repo! 

IMHO, /community is a common entry point for new contributors joining a community, and therefore should include information about the community as a whole -- which may well include information about the Foundation's governance structure, charter, funding, etc, but is not limited to that. I'm not currently convinced we need both, nor which one is better in this situation, nor that it particularly matters.

Happy to discuss tomorrow in the TAC call.

**Comment by lehors** [comment]
My only concerns is duplication of information which leads to more maintenance work but if community is more common than foundation we could maybe rename the foundation repo or delete it in favor of this one?

**Pull request closed without merging**
